SpecialKO/SpecialK

src/control_panel/cfg_d3d11.cpp
Now it's correctly in a new line.
=> Fix "Show OSD in Video Capture" in OGL-IK

src/config.cpp, src/plugins/unclassified.cpp
Updated addresses for the 1.02 game version.
In my tests everything seems to be ok. I compared the addresses with version 1.01 of the game on IDA. I left some comments with the old addresses.
Fixes #13.
=> [Hatsune Miku: Project DIVA Mega Mix+] Addresses for the 1.02 game version.

src/control_panel/cfg_d3d11.cpp
This adds some much needed separation between the two sections in SwapChain Management which would resolve user confusion.
=> Added separation between swapchain mgnt sections

include/SpecialK/control_panel.h, src/control_panel.cpp, src/osd/text.cpp
The on-screen display feature of SpecialK ("OSD") renders certain text on the screen depending on user preferences, such as displaying the current FPS of the game.
The effective font size used for the OSD is the product of two independent configuration variables: `osd.viewport.scale` and `imgui.scale`. However, SpecialK doesn't do anything with the latter of these variables until the user opens the control panel overlay for the first time (e.g., by pressing Ctrl+Shift+Backspace). As a result, the first time the user opens the control panel, the font size of the OSD suddenly changes by a multiplicative factor equal to `imgui.scale`. This is a strange behavior that cannot be intentional.
This changeset ensures that the font size used for the OSD does not change merely because the user opens …
=> Fix OSD font size

src/utility.cpp
SpecialK currently exhibits various problems when dealing with symlinks. For example, if a configuration file is a symlink to some other file, SpecialK will completely ignore that configuration file. This causes problems for me because I use symlinks with some regularity.
It turns out the root cause is that SpecialK's function for checking the size of a file does not work for symlinks because the Windows API call that it uses (GetFileAttributesEx) always returns a file size of zero if the specified target is a symlink. However, the _wstat64 function works correctly for symlinks.
One possible solution would be to completely replace the use of GetFileAttributesEx with _wstat64 instead. However, there are some sutble differences between the two functions and I don't want to risk introducing …
=> Fix SK_File_GetSize for symlinks

src/SpecialK.cpp
https://github.com/SpecialKO/SpecialK/blob/12c62b332f6aae736bbf06dc4913844df3e7e5d4/src/SpecialK.cpp#L905-L910
`<SpecialK>\PlugIns\ThirdParty\dgVoodoo` folder could not be detected for local injection (ddraw/d3d8.dll) because `SK_EstablishRootPath()` was not called and `SK_GetInstallPath()` returned an empty path as a result.
=> Fix dgVoodoo plugin detection for local ddraw/d3d8

depends/derivative/SKinHook/build/libSKinHook.vcxproj
This disables the DebugInformationFormat for libSKinHook which forces the GitHub Actions jobs to fail.
=> Fix ClCompile errors in libSKinHook.vcxproj

src/plugins/elden_ring.cpp
This updates the downloaded PS texture to use the current hash filename and removes any prior files.
=> Elden Ring: Updated to use current PS texture hash

src/render/render_backend.cpp
Fixed `AsyncInit=false` resetting to `AsyncInit=true` in Non-OpenGL Unity games. Some D3D9 games can use `AsyncInit=false` to make D3D9Ex/FlipEx work with global injection.
=> Prevent AsyncInit from re-enabling itself in Non-OGL Unity games

include/SpecialK/config.h, src/config.cpp
Prevents crash on launch due to 'Signature verification of executable failed' by having Special K not hook the window process.
=> Don't hook Serious Sam Fusion 2017's window process

src/control_panel/cfg_plugins.cpp
This just adds ".asi" to the type filter used by the plugin file dialog, which allows those files to be listed by default alongside DLL files.
No other changes seems to be needed for compatibility.
=> Added ASI files to the plugin file dialog

.editorconfig
Adding this file tells Visual Studio to disregard user preferences (default: 4 spaces as indent) and instead use 2 spaces as indent across all files. This ensures the same basic formatting style among contributors.
SKIF has used the same sort of file for awhile now.
=> Added .editorconfig to force 2 spaces as indent

include/SpecialK/config.h, src/config.cpp, src/control_panel/cfg_compatibility.cpp
This allows enabling and disabling render APIs in the compatibility section without affecting the current behaviour of Special K.
This solves #95 and #96 .
=> Added temp parameters for toggled render APIs

src/control_panel.cpp
This moves the ImGui/ImPlot options to a new submenu and allows them to be toggled.
Also uses `ImGui::SeparatorText()` for some fancy header separators.
=> Moved ImGui debug options to a submenu

src/control_panel.cpp
- Don't use app ID for Non-Steam games
- Naively fall back to using window title for other games
=> Improved PCGW link

src/steam/steam_api.cpp
**The Last Remnant** is a Steam game from 2009 with a super-old copy of `steam_api.dll` from September 5, 2008.
This DLL file is only 85.2 KB (87,288 bytes), which falls below the 92 KB minimum that SK currently requires.
Lowering the floor a tiny amount down to 85 KB brings us just beneath and makes this game evaluate as valid.
=> Expect 85 KB minimum for steam_api.dll

include/SpecialK/config.h, src/config.cpp, src/framerate.cpp
When Latent Sync Auto-Bias is enabled, users can toggle a checkbox to specify Target Input Latency in milliseconds (default behavior) or percentage (default value is 50%).
AutoBiasTargetInMs setting was renamed to AutoBiasTarget.
Now it works similarly to [Window.System] XOffset/YOffset setting, for example:
AutoBiasTarget=0.85 (milliseconds) or AutoBiasTarget=85.0% (percentage).
Milliseconds:
Percentage:
=> Added ability to specify target input latency in (ms) or (%)

src/osd/text.cpp
As part of the recent #107 pull request, to fix newline issues with more complex combinations I had to move adding newlines to the top of new sections to instead add newlines to the bottom of a printed section.
This however broke the bottom-aligned OSD, as it always detected the final two newlines of the last printed section and so pushed the OSD up a bit more.
This solves that issue by ignoring the two final newlines.
=> Fixes bottom-aligned OSD

include/SpecialK/render/backend.h, src/control_panel/cfg_d3d11.cpp, src/render/dxgi/dxgi.cpp
Quick and dirty proof of concept of how swapchain overrides could be detailed in the framebuffer and resolution tooltip, to make it more clear to users what the original value was and what it is being overriden to.
=> Show swap chain overrides Special K is applying

src/render/dxgi/dxgi.cpp
Games that natively use either the allow tearing or waitable swapchain DXGI flags will fail being overridden to BitBlt because of that flag, so let's ensure those are never ticked.
=> Disable tearing + waitable when using Flip->BitBlt override

src/config.cpp
Users can now specify `TargetFPS` and `BackgroundFPS` as refresh rate factor:
- `TargetFPS=1/1`, `BackgroundFPS=1/2` and so on...
The factor value only applies on first launch and gets converted to a decimal value (actual FPS limit) for subsequent launches.
=> Added ability to specify TargetFPS/BackgroundFPS as refresh rate factor

src/control_panel.cpp
- Added more Refresh Rate Factors in control panel (`1/2, 1/3, 1/4, 1/5...` instead of `1/2, 1/4, 1/8, 1/16...`).
- If there are multiple similar factors (30.9, 30.5 ... 30.0), only the lowest one (30.0) will be listed.
- Added Latent Sync 3x mode (currently disabled like the other 2x and 4x modes).
- Once enabled, Latent Sync scan mode list will be appended with even higher modes when a user selects the current highest mode (selecting 4x adds 5x/6x, selecting 6x adds 7x/8x...).
- The selected factor will be remembered to allow seamless transition between regular and Latent Sync limiters (selecting regular 1/N factor and then checking Latent Sync checkbox will no longer reset FPS limit to 1:1).
=> Add more Refresh Rate Factors

include/SpecialK/config.h, src/SpecialK.cpp, src/control_panel.cpp, src/core.cpp, src/diagnostics/compatibility.cpp, src/render/d3d9/d3d9.cpp, src/render/dxgi/dxgi.cpp, src/render/render_backend.cpp
- Updated `SK_dgVoodoo_CheckForInterop (...)` to detect all dgVoodoo DLLs/APIs (D3D9/D3D8/DDraw/Glide) instead of D3D9 only.
- Applied dgVoodoo compatibility settings (`UseFactoryCache=false`, `SkipRedundantModeChanges=true`) for local injection as well.
- Disabled `AsyncInit` for global D3D8/DDraw injection (dgVoodoo Plug-In).
- Disabled dgVoodoo Plug-In if a D3D8/DDraw game is already translated.
- Fixed some typos in `dgVoodoo_Nag (...)`
=> Detect D3D8/DDraw/Glide in SK_dgVoodoo_CheckForInterop (...)

src/render/render_backend.cpp
- Fixed empty Active Render API name that occasionally appeared after a delayed injection.
=> Update Active API if its name is empty

resource/shaders/HDR/basic_hdr_shader_ps.hlsl
Before this fix the HDR10 gamut visualizer analyzed the scRGB image. So there was no difference between the gamut visualizers.
With this fix the result of the applied transfer function for HDR10 is used as base for the analysis.
=> Fix hdr10 gamut visualizer

include/SpecialK/config.h, include/SpecialK/render/ngx/ngx_dlss.h, src/config.cpp, src/control_panel/cfg_osd.cpp, src/osd/text.cpp, src/render/ngx/ngx.cpp
Made various changes to the DLSS indicator.
* Added output resolution
* Merged all the options into a single line
* Moved its placement in the OSD to above the GPU stats
* * Also added necessary padding etc to fit its new placement
* Changed the relevant control panel UI elements to reflect the changes
=> Improved DLSS indicator

resource/shaders/HDR/basic_hdr_shader_ps.hlsl
In the current implementation, the hue shifts when using SDR Gamma Boost (it changes both when lowering or raising SDR Gamma Boost).
This commit fixes the behavior to be based on Luminance instead.
=> Fix hue shifting when using SDR Gamma Boost

include/SpecialK/input/input.h, include/imgui/imgui_user.inl, src/input/raw_input.cpp, src/input/winhook_input.cpp
Replaces PR https://github.com/SpecialKO/SpecialK/pull/285.
This PR fixes various issues with the optimization in backup input thread.
The most notable change for users is fixing the inability to open the SpecialK overlay in some games, by disabling the optimization when the game uses a RawInput keyboard with `RIDEV_NOLEGACY` flag or a low-level keyboard hook, which may cause `GetKeyboardState` to not update.
I am not sure whether the low-level keyboard hook disable is required, but the RawInput part was needed for Resident Evil: Village.
However FWIW, as I already mentioned, I am not sure whether the call to `GetKeyboardState` from background thread without message queue processing is compliant with [docs](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboards …
=> Backup input thread GetKeyboardState optimization fixes

src/render/d3d9/d3d9.cpp
`D3D9SwapChainEx::Present` vftable hook is being triggered in d9vk `D3D9Device(Ex)::Present` because it is using an internal instance of `D3D9SwapChainEx`
Detect double processing and avoid it
=> d9vk double processing fix

.editorconfig, SpecialK.vcxproj, SpecialK.vcxproj.filters, depends/derivative/SKinHook/build/libSKinHook.vcxproj, depends/src/DirectXTex/DirectXTex_Desktop_2015.vcxproj, depends/src/lzma/libzma/libzma.vcxproj, include/SpecialK/config.h, include/SpecialK/plugin/plugin_mgr.h, src/config.cpp, src/core.cpp, src/plugins/watch_dogs.cpp
Currently implemented features:
- Remove VMProtect page protection (Unhook NtProtectVirtualMemory from disk)
- MouseAccelFix: https://github.com/Sad-Gamers/Camera-Tools-For-Watch_Dogs
Tested on Steam (Asia) build of the game.
---
https://discord.com/channels/345656208411328514/1169196867280703589/1391453548818206762
=> Watch_Dogs: New plugin

include/SpecialK/config.h, include/SpecialK/core.h, include/SpecialK/framerate.h, src/command.cpp, src/config.cpp, src/control_panel.cpp, src/control_panel/cfg_d3d11.cpp, src/core.cpp, src/framerate.cpp, src/render/d3d9/d3d9.cpp, src/render/dxgi/dxgi.cpp
- Added new tearing modes for regular V-Sync:
- Always Off (Low Latency): temporarily lowers FPS limit if Render Latency exceeds 1 frame.
- Adaptive V-Sync: temporarily turns V-Sync Off (without enabling Latent Sync) if FPS is unstable or Render Latency exceeds 1 frame.
- Added new tearing modes for Latent Sync:
- Always Off (Low Latency): temporarily lowers FPS limit if Render Latency exceeds 1 frame.
- Adaptive (Prefer On): only disables tearing if FPS is unstable.
- Adaptive (Prefer Off): only enables tearing if FPS is unstable or Render Latency exceeds 1 frame.
- Made Latent Sync non-tearing modes functional in D3D9 / FSE games by forcing Presentation Interval 1.
- Reset frame limiter when V-Sync gets stuck at high variation or ±0.0 ms input latency (still experimental and does not …
=> Added Adaptive Tearing options and enabled Latent Sync 2x.. modes
